In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
dataset=pd.read_csv("social_ads.csv")
dataset.head(2)

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0

In [11]:
dataset.isnull().sum().sum()

0

In [12]:
x=dataset.iloc[:,:-1]
y=dataset[["Purchased"]]
x.head(),y.head()

(   Age  EstimatedSalary
 0   19            19000
 1   35            20000
 2   26            43000
 3   27            57000
 4   19            76000,
    Purchased
 0          0
 1          0
 2          0
 3          0
 4          0)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ss=StandardScaler()
x=pd.DataFrame(ss.fit_transform(x),columns=x.columns)
x.head()

        Age  EstimatedSalary
0 -1.781797        -1.490046
1 -0.253587        -1.460681
2 -1.113206        -0.785290
3 -1.017692        -0.374182
4 -1.781797         0.183751

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
dt=DecisionTreeClassifier(max_depth=5) #max_depth is pruning .it is pre pruning
dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [19]:
dt.score(x_test,y_test)*100

90.0

In [23]:
dt.score(x_train,y_train)*100

93.4375

In [20]:
dt.predict([[19,19000]])

C:\Users\Suchana\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [21]:
from sklearn.tree import plot_tree

In [22]:
plot_tree=(dt)
plt.show()